# Generated by Django 4.2.7 on 2023-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
        migrations.AddField(
            model_name='post',
            name='impression',
            field=models.CharField(default='headline for your blog!', max_length=255),
        ),
    ]
