# Generated by Django 4.2.7 on 2023-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_remove_post_snippet_post_impression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='impression',
            field=models.CharField(max_length=255),
        ),
    ]
