# Generated by Django 4.2.7 on 2023-11-20 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_alter_post_impression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='impression',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
